### ISSUE TITLE
acorn-private-class-elements is not bundled

### ISSUE THREAD

**Issue by ngzhian** [acornjs/acorn-private-methods#5]
Using `npm run build`, I see:

```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
acorn-private-class-elements (imported by index.js)
```

It looks like https://rollupjs.org/guide/en/#with-npm-packages can fix this. Is it okay for me to put up a patch that does this? Or would you rather `acorn-private-class-elements` be required at runtime?

**Comment by adrianheine** [comment]
What would be the benefits of bundling?
